### ISSUE TITLE
results are very hard to read

### ISSUE THREAD

**Issue by arashnm80** [tact-lang/tact-by-example#15]
the box in lower right corner is very small and shows only 1 or 2 lines at a time so most of results are unreadable and I have to copy and paste them to an outer editor every time. can you do sth about it?

**Comment by novusnota** [comment]
You can hover the mouse over the area in-between the code and the buttons with logs, and then click & pull it to adjust pane heights to your liking. Check out the screenshots below.

Hover over this area:

![Area to hover over](https://github.com/tact-lang/tact-by-example/assets/68142933/157f0eaa-314f-4aae-9b69-8b04c6211321)

And then pull it up to increase the space for buttons & logs pane:

![image](https://github.com/tact-lang/tact-by-example/assets/68142933/b233bd0f-86cb-493d-9e12-d70f6ff364b3)

Hope this covers your issue!
