### ISSUE TITLE
Example 06-contract-deploy-another doesn't work

### ISSUE THREAD

**Issue by behrang** [tact-lang/tact-by-example#7]
Presseing `Send "deploy 2nd" to 1` button shows this error:

```
Error: Invalid message type
```

I couldn't find the error myself to fix it and send a PR.

**Comment by SC-One** [comment]
yeah , it seems that sending `"deploy next"` while receiver need to take `"deploy 2nd"`.

**Comment by novusnota** [comment]
This was successfully resolved in #20
